"""add local_currency to open_positions

Revision ID: 345370a998ec
Revises: 48ace06dd2a5
Create Date: 2026-05-19 23:26:14.537495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345370a998ec'
down_revision: Union[str, None] = '48ace06dd2a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('open_positions', sa.Column('local_currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('open_positions', 'local_currency')
    # ### end Alembic commands ###
