"""initial schema

Revision ID: 48ace06dd2a5
Revises: 
Create Date: 2026-05-19 20:21:50.596022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ace06dd2a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('yf_ticker', sa.String(length=30), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('closed_positions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instrument_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('profit_loss_pln', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dividends',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instrument_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount_local', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('local_currency', sa.String(length=3), nullable=False),
    sa.Column('amount_pln', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('per_share', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('per_share_currency', sa.String(length=3), nullable=True),
    sa.Column('external_id', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('open_positions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instrument_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_cost_local', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('current_price_currency', sa.String(length=3), nullable=True),
    sa.Column('current_value_local', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_value_pln', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pln', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('last_price_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instrument_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('account_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('instrument_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount_local', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('local_currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('amount_pln', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('external_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('price_history')
    op.drop_table('open_positions')
    op.drop_table('dividends')
    op.drop_table('closed_positions')
    op.drop_table('instruments')
    op.drop_table('fx_rates')
    op.drop_table('accounts')
    # ### end Alembic commands ###
